/*
 * NumOS — FontStruct CASIO-Calculator-Font (2019 UI face) Declarations
 * Copyright (C) 2026 Juan Ramon
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * LVGL font declarations for the three CASIO FX-9860GII UI face sizes:
 *   casio_ui_12  — fontLcdSm (12pt, bpp=2)
 *   casio_ui_18  — fontLcd   (18pt, bpp=4)  → theme fontUi under casio
 *   casio_ui_26  — fontLcdLg (26pt, bpp=4)  → theme fontDisplay under casio
 *
 * Derived from FontStruct CASIO-Calculator-Font (2019 release) by TH3_C0N-MAN
 * (https://fontstruct.com/fontstructions/show/1672425),
 * used under the Creative Commons Attribution 3.0 Unported licence
 * (https://creativecommons.org/licenses/by/3.0/).
 *
 * Generated by scripts/generate_casio_ui_font.sh using lv_font_conv.
 */

#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(casio_ui_12);
LV_FONT_DECLARE(casio_ui_18);
LV_FONT_DECLARE(casio_ui_26);

#ifdef __cplusplus
}
#endif