/*
 * NumOS — FontStruct CASIO-Calculator-Font Declarations
 * Copyright (C) 2026 Juan Ramon
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * LVGL font declarations for the three CASIO-Calculator-Font sizes:
 *   casio_math_18  — Display/Text style  (18pt)
 *   casio_math_12  — Script style         (12pt, ~70% of display)
 *   casio_math_8   — ScriptScript style   ( 8pt, ~55% of script)
 *
 * Derived from FontStruct CASIO-Calculator-Font by TH3_C0N-MAN
 * (https://fontstruct.com/fontstructions/show/1475969),
 * used under the Creative Commons Attribution-ShareAlike 3.0 Unported licence.
 *
 * Generated by scripts/generate_casio_math_font.sh using lv_font_conv.
 */

#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

LV_FONT_DECLARE(casio_math_18);
LV_FONT_DECLARE(casio_math_12);
LV_FONT_DECLARE(casio_math_8);

#ifdef __cplusplus
}
#endif
